### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by goeppes** [Civcraft/AttrHider#13]
It is unclear what this plugin specifically does. 

For example:
1. It says that potion duration data is hidden. Is only potion effects or should it be all status effects?
2. Should all enchantments be hidden, or can a player see his own enchantments? Also for some reason Unbreaking 1 is being added to all enchanted equipment, what is this for?

In order to better understand the purpose of this plugin, it might also be good to describe the problem it addresses.

**Comment by Maxopoly** [comment]
The remaining duration of all status effects on other players is obfuscated by always being set to the same value

The equipment modifying is only done for packets which update the armour of another player, so it will never affect any of your own inventory. Unbreaking 1 is added if the item was enchanted previously, this is done so the item still glows/shines and still indicates whether it's enchanted or not.

**Comment by Maxopoly** [comment]
Problem adressed with hiding buff duration is removing the advantage someone could get through a hacked client, which shows timers for remaining potions. That data is sent to every nearby client and could give a big advantage in PvP.

Hiding the health of players, durability of armour and it's enchants has exactly the same motivation, don't send other clients information they dont need, which they could abuse.
