### ISSUE TITLE
Mysterious disconnects 

### ISSUE THREAD

**Issue by drjawa** [Civcraft/AttrHider#3]
In an attempt to fix the other disconnect issue, a test was done with enchantment spoofing disabled, but the results were similiar. However, there were zero stacktraces or results from netty.

Maybe related to health spoofing. I might just change it to send a set value (20) instead of randomly generating a value.

**Comment by suirad** [comment]
This is over a year old. I don't see any commits mentioning it. Does this still happen?

**Comment by erocs** [comment]
AttrHider hasn't been used because of these issues but nobody has dug in and found the root cause. These issues are suspected to be an error with ProtocolLib while rebuilding the modified packets.

**Comment by suirad** [comment]
Interesting. Maybe its worth a re-approach to finish along with other upcoming features.
I have been reading up on the protocol lately, i could take a look into this after i am finished going through other bugs.

**Comment by suirad** [comment]
Good to close?
